# Enable automatic update checks.
auto-update: true

# Add custom advancements to the vanilla advancements menu (experimental).
use-advancements-api: true

# Announce completed advancements in chat.
announce-advancements: true

# Add the Slimefun Advancements button to the Slimefun Guide.
add-advancements-to-guide: true

# Enable additional diagnostic logging.
debug: false

# Run Bukkit.reloadData after removing registered advancements.
# This may cause a short server pause on large servers.
reload-data-on-adv-remove: true
